name: 'OpenAI Generated PR Descriptions'
description: 'Utilizes advanced AI algorithms to automatically generate pull request descriptions.'
author: 'Sajel Shah - Forked From Rock Chen'
runs:
  using: 'node20'
  main: './dist/bundle.js'
inputs:
  ai_name:
    description: 'The name of AI, currently just supports open-ai'
    required: true
    default: 'open-ai'
  api_key:
    description: 'API key for authenticating with OpenAI service. Ensure it has the necessary permissions for generating content.'
    required: true
  github_token:
    description: 'GitHub token with repository permissions to access and modify pull requests. Make sure it has at least read and write access to pull requests.'
    required: true
  temperature:
    description: 'Controls the randomness of the generated descriptions. A value between 0.0 (more deterministic) and 1.0 (more creative).'
    required: false
    default: '0.7'
  ignores:
    description: 'AI will not analyze changes to files or folders in this array'
    required: false
outputs:
  description:
    description: 'The AI-generated description for the pull request, providing context and details for reviewers.'
branding:
  icon: 'align-justify'
  color: 'purple'
