name: AI-Powered PR Description Generator

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - master

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate PR Description
        uses: ./
        with:
          ai_name: 'open-ai'
          api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GH_TOKEN }}
          temperature: 0.7  # Optional: default is 0.7
